### ISSUE TITLE
Version error on compressed dbexport.sql

### ISSUE THREAD

**Issue by BenSeguin** [gabrielmartell/COMP3005-Project-Template#14]
Hey Gabe, for our final project submission we compressed the dbexport as instructed, however when attempting to run it on the course VM, I run into this error:
![Screenshot 2024-04-11 110133](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/93552944/b44f2dc4-655d-4b20-a0b0-ee9399b5b35e)

None of our groupmates really understand how github works in this capacity, do you know what this error means or how we can fix it?

**Comment by Fail-staff** [comment]
to add aditional clarification, we were using LFS for this .sql file as instructed.

Before we did that, when we were just using the raw dbexport.sql file it was working fine tho

**Comment by gabrielmartell** [comment]
Hi @Fail-staff,

When you convert your dbexport.sql file into an LFS, it changes the file into a pointer (since LFS are just pointers), and in turn, it changes your dump file text. If you looked in your dbexport.sql now, you can see that it's actually not your initial dbexport.sql file, but rather the LFS pointer information that references it. 

To test it, you would need to convert the LFS back into the regular .sql file.
I believe this can be done with the following snippet: `git lfs pull --include *.sql`

Please let me know if this was the case,

Thanks!
Gabe

**Comment by gabrielmartell** [comment]
Yes - well technically, the _autograder_ marks your submission, but nonetheless yes.
