### ISSUE TITLE
Role of dbexport.sql

### ISSUE THREAD

**Issue by ca-sajad** [gabrielmartell/COMP3005-Project-Template#3]
Just to make sure I'm doing it correctly:

- I've created an empty database called "project_database"
- then, exported the main database (populated using the json files) to a file called query_database
- then deleted dbexport.sql file and replaced "dbexport.sql" in load_database(cursor, conn) with "query_database"
- then added queries to Q_n functions

The third step isn't mentioned in README or project document but I found it necessary. Is this how it should be?

**Comment by gabrielmartell** [comment]
Hi @ca-sajad 

You are correct with the first step...
Create an empty database called "project_database". 

This is because a database cannot DROP the current database its connected to, which is why there exists a "query_database", so that this database can be queried, created and dropped without running into connection and cursor fatal errors, where as "project_database" is your root connection.

This is where there might be some confusion...
In the queries.py, the code _creates_ a database called "query_database". 
Initially, it's empty, but its then and there that the code grabs your dbexport.sql and fills this query_database with data, it does this on line 53 in the load_database function:
**command = f'psql -h {host} -U {user} -d "query_database" -a -f {os.path.join(dir_path, "dbexport.sql")}'.**

You do not need to create a "query_database" yourself - the only things you need to do is:
- Write your queries in the Q_n functions.
- Replace the dbexport.sql in **this** repository with your own database export containing the JSON data you parsed to fill it up initially, as the dbexport.sql in this repository is pure example.

In a sense, you did already do this with your approach that you listed - **but** you didn't need to since the code does it for you already.
I would advise following my checklist above (i.e, only writing your queries and replacing dbexport.sql with your own) since any other submissions that are NOT your **queries.py, dbexport.sql and json_loader folder** will void your submission. In addition, any modification to the base code will also void the submission.

I'll keep this issue open in case you have any other questions!

Thanks!

**Comment by ca-sajad** [comment]
Thank you. Now that makes sense.
When I run the code, it creates csv files (with correct values I hope) and prints the times but also prints lots of error messages like this for each query:
psql:/Users/sajad/PycharmProjects/comp3005_project_queries/dbexport.sql:495: ERROR:  relation "events" already exists
or
psql:/Users/sajad/PycharmProjects/comp3005_project_queries/dbexport.sql:1644023: ERROR:  constraint "managers_country_id_fkey" for relation "managers" already exists
Is it normal?

**Comment by gabrielmartell** [comment]
Hmmmm... in all honesty I'm not too as of right now.

Assuming that you didn't change **any base code,** this could be one of the options:
- You did not properly parse the JSON data into your database, and thus your dbexport.sql file is wrong.
- If these error messages are printing **BEFORE** the times are printed, it is just garbage errors and don't necessarily break your submission and originate from running the dbexport file.
- You still have a database named "query_database" still created, and didn't necessarily remove it when you fixed your initial code hence why **events** or **managers_country_id_fkey** still exists and showing errors.

If these aren't it, maybe double check if the queries.py code is still the same as the one in this repository.

Please let me know if this helps!

Thanks!

**Comment by ca-sajad** [comment]
So, it seems the code is trying to create/load the query_database multiple times (once for each Q_n).
In Q_1 I replaced `connection = load_database(cursor, conn)` with the code in `load_database(cursor, conn)` function. But in the  `load_database(cursor, conn)` itself removed the try-except block, so now Q_1 loads the query_database and other Q_n functions just use it without the need to load it again.
After these changes I don't see the errors anymore.
I won't use this version to submit my project, but just wanted to get to the bottom of the problem, making sure it's not from my database.
Thanks

**Comment by gabrielmartell** [comment]
No problem!
The queries.py is designed like that - to drop and create the same database to avoid any alterations to the database (as a just in case).

I'm glad you were able to solve this issue, please feel free to open up another if you run into other issues!

Thanks!
