### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by EuropeanB** [gabrielmartell/COMP3005-Project-Template#5]
Should we change the dbname, password, host and port in queries.py?
There are three places where these parameters are used.
If we don't change these default settings, an error will occur:
connection failed: FATAL:  password authentication failed for user "postgres"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"

**Comment by gabrielmartell** [comment]
Hi @EuropeanB,

As stated in the readme file, 
_"You should create a database named "project_database" for testing, with the password, user, port and host are also the same as the ones listed in the code."_

Therefore, you shouldn't change **anything** in the queries.py - you should instead change your database to fit these requirements.

Please feel free to create a new issue if you have any other questions!
Gabe

**Comment by EuropeanB** [comment]
So just like I said: If we don't change these default settings, an error will occur:
connection failed: FATAL: password authentication failed for user "postgres"
connection to server at "127.0.0.1", port 5432 failed: FATAL: password authentication failed for user "postgres"

**Comment by gabrielmartell** [comment]
Right,
You have to set the password of default user "postgres" to "1234". This issue is caused because user "postgres" has no password yet, or the password you have set is incorrect.

**Comment by EuropeanB** [comment]
It doesn't make sense.
I just copied your code from your queries.py about a few minutes ago and I didn't change anything, including the query areas.
I still get this error after running this script:
connection failed: FATAL:  password authentication failed for user "postgres"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"

**Comment by gabrielmartell** [comment]
That's fine - that's what you are supposed to do!
When that error occurs, its not caused by the queries.py file (code), **its caused by your PostgreSQL settings (internal).**

When you install PostgreSQL build, I'm assuming you have chosen the following options in its installation:

- PostgreSQL Server
- pgAdmin 4
- CommandLine Tools

With this installation also includes a **user**, which is some profile that determines which databases this **user** can access. By default, one "master" user is named "postgres.", but no password is set yet for this user. 

When I refer to setting the "postgres" password to "1234", I am actually talking about accessing the "postgres" named user in your PostgreSQL and changing its password to "1234" - not changing the code. 

In your Linux terminal, try doing the following commands to be prompted on creating a password for the user:

**psql -U postgres
\password**

I'm _pretty sure_ this works. You can also try using pgAdmin 4, as this also prompts you to create a **master password**.

**Comment by EuropeanB** [comment]
The script finally ran after changing some settings.
So how long does this script take to complete?
Can we run it for multiple times?
Because we may run this script multiple times in this week depend on what need to modify.
And seems like my Virtual machine can't stand on it
<img width="486" alt="image" src="https://github.com/gabrielmartell/COMP3005-Project-Template/assets/55248830/a5bf6157-cd57-4641-b400-740c475ffd14">

**Comment by gabrielmartell** [comment]
Hi @EuropeanB ,

Sorry for the delayed response - I didn't see any notifications about this issue.
The script **shouldn't** take long to run, at all. At most, for me at least, it takes me about 10 seconds.
You can definitely run this script multiple times - its not only meant for the autograder, but for you to test yourself.
If I recall correctly, if the VM isn't able to hold on its own I think you can dedicate more power to it in the VM settings.

Thanks!
Gabe
