### ISSUE TITLE
queries.py usage

### ISSUE THREAD

**Issue by jacob-w-bonner** [gabrielmartell/COMP3005-Project-Template#6]
Hello,

I have been attempting to test my queries with the provided queries.py on a Linux environment. Although the work I have done across the term was done entirely on Windows, I believe I have set up psycog3 and PostgreSQL correctly on a Ubuntu VM, however I am consistently running into problems with running the file. The current issue I am having is an authentication error, despite modifying passwords in the queries.py file to those of my previous databases (they would be changed back to '1234' before submission). In case this is relevant, the database setup script, queries.py, and exported database were all made/worked on in Windows and later transfered to Linux. Any guidance towards how to effectively execute the file, or any essential knowledge on the setup and usage of PostgreSQL on Linux that might easily be missed, would be appreciated.

Thanks

**Comment by gabrielmartell** [comment]
Hi @jacob-w-bonner,

I'm going to _assume_ that you have a _password authentication error_. 
This is really only caused because your password is wrong, which could mean **the password you set for the user "postgres" doesn't match the code**. In my code there are **three** password assignments, but with the **new updated queries.py file**, can just be changed once in the header of the script.

The queries.py file was made for execution on the Linux environment. Therefore, if you modified it to work on Windows, but then tried to revert it back, you could have missed something during that process. If I remember correctly, the dbexport.sql should be fine universally. Nonetheless, if you feel like that is the case, and assuming you haven't already, I advise that you reinstall the queries.py file and then move your queries over.

In terms of guidance for PostgreSQL setup, I will refer back to a [closed issue](https://github.com/gabrielmartell/COMP3005-Project-Template/issues/5) from another student who also had a connection/authentication error. My reply might be helpful to you, or might not be.
To reiterate my response:

> When you install PostgreSQL build, I'm assuming you have chosen the following options in its installation:
>
> - PostgreSQL Server
> - pgAdmin 4
> - CommandLine Tools
>
> With this installation also includes a user, which is some profile that determines which databases this user can access. By default, one "master" user is named "postgres.", but no password is set yet for this user.
When I refer to setting the "postgres" password to "1234", I am actually talking about accessing the "postgres" named user in your PostgreSQL and changing its password to "1234" - not changing the code.
>
> In your Linux terminal, try doing the following commands to be prompted on creating a password for the user:
>
> psql -U postgres
> \password
>
> I'm pretty sure this works. You can also try using pgAdmin 4, as this also prompts you to create a master password.

If you still have any issues please let me know, I'll keep this issue open!
Gabe

**Comment by gabrielmartell** [comment]
Hi @jacob-w-bonner,
I'm going to close this issue now assuming it's all settled. 

Please feel free to open up another issue if there's anything else I can help you with!

Thanks!
Gabe
