### ISSUE TITLE
queries.py Full of Errors

### ISSUE THREAD

**Issue by JoeyVilleneuve** [gabrielmartell/COMP3005-Project-Template#8]
Hi there,
I have been consistently running into problem after problem attempting to run queries.py, and now I am completely stuck.

Here is what I have done so far:
1. Made a psycopg3 script that creates a db "project_database" of my own design, then populates it with the data from the JSON files.
2. Found out that "queries.py" doesn't work in Windows. Entered a Ubuntu environment from one of my class' VMs, installed postgreSQL & pgAdmin.
3. Ran my script and confirmed that the database is correct and populated using pgAdmin.
4. Exported the db to a .sql file using "pg_dump -U postgres -h localhost project_database >> dbexport.sql" (inside Ubuntu to get UTF-8 encoding, which was a whole issue in itself). The result is a whopping 180mb in size, causing more problems related to my VM's allocated disk space as well as GitHub's maximum single file size.
5. Found a way to run "queries.py" inside a shared folder.

Finally, queries.py actually runs, but now it is riddled with errors. I can see it going over all of my tables and all of the data using the correct names, but I can see a bunch of error prints along the way. I have attached an image of the end of the print.

I apologize for the harsh tone, but I have spent more time just trying to understand what is expected from me and getting the autograder to work than actually doing the project, which I think is a major problem. Please let me know what I can do so I can finally get started on queries and help my groupmates understand how to start.

Thanks for your time,
Joey V.

**Comment by JoeyVilleneuve** [comment]
![Screenshot_584](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/61750766/bcd61af2-56dc-4c8e-aaa7-ea598ed79d4d)

**Comment by gabrielmartell** [comment]
Hi @JoeyVilleneuve,

No need to apologize, I understand that these last days are becoming stressful as they come. 
But to get straight to the point, 

Your snippet of your output, and that large blob of text, is simply your dbexport.sql being dumped into the newly created database, as seen in the last line of the output:
> "PostgreSQL database dump complete"

These aren't errors, they are a log of the dump. I've also mentioned this in my README.md,
> "The other prints before the execution times are printed are from the dump files, which can be ignored."

Although, I do not really mention what the print statements are, so that's an error on my part.

As for the following **[ERROR] Error getting time.** and **'NoneType' object is not iterable** errors, these are because your next 9 queries are empty. There is no next fix - you are good to proceed with finishing your queries,

I won't close this issue just yet in case you have any other questions or concerns about the queries.py,
Good Luck!

Gabe

**Comment by JoeyVilleneuve** [comment]
Oh, okay... Phew. Thanks a lot for the clarification @gabrielmartell , I'll let you know if anything else pops up.

**Comment by gabrielmartell** [comment]
Hi @JoeyVilleneuve,

I'm assuming all was solved - if anything else does pop up please feel free to shoot another issue towards my way!

Thanks,
Gabe
